export const errorHandler = (err, req, res, next) => {
  console.error("❌ Erro interno:", err.stack);
  res.status(500).json({ error: "Erro interno do servidor" });
};